package:
  name: dsistudio
  version: 2021.10
source:
  - git_url: http://github.com/frankyeh/DSI-Studio
    folder: src
  - git_url: http://github.com/frankyeh/TIPL
    folder: src/tipl

build:
  noarch: generic

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - git
    - curl
    - make
    - unzip
  
  run:
  


outputs:
  - name: dsistudio
    version: 2021.10

about:
  home: http://dsi-studio.labsolver.org
  license: GPL
  summary: "Diffusion MRI Tractography Tool"

