###########################################################################
path_classifiers:
  test:
    - test
extraction:
  cpp:
    prepare:
      packages:
        - build-essential
        - gcc
        - libffi-dev
        - libgl-dev
        - libpoppler-qt5-dev
        - libqt5svg5-dev
        - libssl-dev
        - qt5-default
        - qt5-qmake
        - qtchooser
        - qtbase5-dev
        - qtbase5-dev-tools
        - qttools5-dev
        - software-properties-common
        - zlib1g-dev
    configure:
      command:
        - git clone https://github.com/frankyeh/TIPL.git
        - mv TIPL tipl
        - qmake dsi_studio.pro
    index:
      build_command:
        - make
  python:
    after_prepare:
      - export PATH=$LGTM_WORKSPACE/tools:$PATH
