package:
  name: dsistudio
  version: 2021.10
source:
  - git_url: http://github.com/frankyeh/DSI-Studio
    folder: src
  - git_url: http://github.com/frankyeh/TIPL
    folder: src/tipl
  - url: https://www.dropbox.com/s/pib533irglhnwy7/dsi_studio_64.zip
    folder: dsi-studio-64

build:
  noarch: generic

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - git

outputs:
  - name: dsistudio
    version: 2021.10

about:
  home: http://dsi-studio.labsolver.org
  license: GPL
  summary: "Diffusion MRI Tractography Tool"

