package:
  name: dsistudio
  
source:
  git_url: http://github.com/frankyeh/DSI-Studio.git

build:
  noarch: generic

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - git

about:
  home: http://dsi-studio.labsolver.org
  license: GPL
  summary: "Diffusion MRI Tractography Tool"
