version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build_docker:
    environment:
      TZ: "/usr/share/zoneinfo/America/New_York"
      SCRATCH: "/scratch"
    docker:
      - image: ubuntu:20.04
    working_directory: /tmp/src/DSI-Studio
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          no_output_timeout: 3h
          command: |
            # Build docker image
            e=1 && for i in {1..5}; do
              docker build --file build_packages/ubuntu_2004/Dockerfile --rm=false -t dsistudio/dsistudio:latest . && e=0 && break || sleep 15
            done && [ "$e" -eq "0" ]
      - run:
          name: Deploy to Docker Hub
          no_output_timeout: 40m
          command: |
            if [[ -n "$DOCKER_PASS" ]]; then
              docker login -u $DOCKER_USER -p $DOCKER_PASS
              docker push dsistudio/dsistudio:latest
            fi

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_docker:
          filters:
            tags:
              only: /.*/


