version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build_docker:
    environment:
      TZ: "/usr/share/zoneinfo/America/New_York"
      SCRATCH: "/scratch"
    docker:
      - image: docker:18.06.1-ce-git
    working_directory: /tmp/src/DSI-Studio
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          no_output_timeout: 3h
          command: |
            # Build docker image
            e=1 && for i in {1..5}; do
              docker build \
                --rm=false \
                -t dsistudio/dsistudio:latest . \
              && e=0 && break || sleep 15
            done && [ "$e" -eq "0" ]
      - run:
          name: Deploy to Docker Hub
          no_output_timeout: 40m
          command: |
            if [[ -n "$DOCKER_PASS" ]]; then
              docker login -u $DOCKER_USER -p $DOCKER_PASS
              docker push dsistudio/dsistudio:latest
            fi



  build_windows:
    executor:
      name: win/default
    steps:
      # This needs to be replaced with the windows build
      - run:
         command: $(echo hello | Out-Host; $?) -and $(echo world | Out-Host; $?)
         shell: powershell.exe
      - run:
         command: echo hello && echo world
         shell: bash.exe
      - run:
         command: echo hello & echo world
         shell: cmd.exe

  deployable:
    docker:
      - image: busybox:latest
    steps:
      - run: echo Deployable!


workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_docker:
          filters:
            tags:
              only: /.*/

      - build_windows:
          filters:
            tags:
              only: /.*/

      - deployable:
          requires:
            - build_docker
            - build_windows
          filters:
            branches:
              only: master
            tags:
              only: /.*/
