name: Setup Test Environment
inputs:
  test_file:
    required: true
runs:
  using: "composite"
  steps:
    - name: Download and Unzip
      run: |
        curl -L "https://github.com/frankyeh/DSI-Studio/releases/download/2021.12.03/dsi_studio_ubuntu_2004.zip" -o 1.zip
        curl -L "${{ inputs.test_file }}" -o 2.zip
        unzip 1.zip
        unzip 2.zip
        rm -fr *.zip
