name: Build Nightly 

on: workflow_dispatch
  
jobs:
  linux-build:
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-18.04]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    env:
      CXX: g++-9
      CFLAGS: -Werror
      QT_SELECT: qt5
    steps:
    - uses: actions/checkout@v1
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: 5.12.0
        modules: qtcharts qtopengl    
    - name: Install Boost
      run: |
        sudo apt update
        sudo apt full-upgrade -y 
        sudo apt install -y --no-install-recommends libboost-all-dev zlib1g-dev ca-certificates mesa-common-dev libglu1-mesa-dev libqt5opengl5-dev gcc-9 g++-9
        sudo apt-get clean
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 9
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-9 9
    - name: Download TIPL and Atlases
      run: |
        git clone https://github.com/frankyeh/TIPL.git
        git clone https://github.com/frankyeh/DSI-Studio-atlas.git
        rm -fr DSI-Studio-atlas/.git
        mv TIPL tipl
    - name: Build DSI Studio
      run: |
        mkdir -p build
        cd build
        qmake ../dsi_studio.pro
        make
    - name: Packaging
      run: |
        mkdir dsi_studio_ubuntu
        cp -R other/*  dsi_studio_ubuntu    
        chmod 755 build/dsi_studio
        mv build/dsi_studio  dsi_studio_ubuntu
        mv DSI-Studio-atlas  dsi_studio_ubuntu/atlas   
        zip -r dsi_studio_ubuntu_${{ matrix.os }}.zip  dsi_studio_ubuntu
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: "dsi_studio_latest_${{ matrix.os }}"
        path: "*.zip"
        if-no-files-found: error
        retention-days: 90

  macos-build:
    strategy:
      matrix:
        os: [macos-11]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    env:
      CFLAGS: -Werror
    steps:
    - uses: actions/checkout@v1
    - name: Install Qt
      run: |
        brew update
        brew install qt5
        brew install boost
    - name: Download TIPL and Atlases
      run: |
        git clone https://github.com/frankyeh/TIPL.git
        git clone https://github.com/frankyeh/DSI-Studio-atlas.git
        rm -fr DSI-Studio-atlas/.git
        mv TIPL tipl
    - name: Build DSI Studio
      run: |
        mkdir -p build
        cd build
        export PATH="/usr/local/opt/qt@5/bin:$PATH" && export LDFLAGS="-L/usr/local/opt/qt@5/lib" && export CPPFLAGS="-I/usr/local/opt/qt@5/include" && export PKG_CONFIG_PATH="/usr/local/opt/qt@5/lib/pkgconfig"
        qmake ../dsi_studio.pro QMAKE_INCDIR=/usr/local/Cellar/boost/1.76.0/include
        make
        cd ..
    - name: Packaging
      run: |
        mv other/* build/dsi_studio.app/Contents/MacOS/
        mv DSI-Studio-atlas build/dsi_studio.app/Contents/MacOS/atlas
        mv build/dsi_studio.app .
        /usr/local/opt/qt@5/bin/macdeployqt dsi_studio.app
        zip -r dsi_studio_mac.zip  dsi_studio.app
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: "dsi_studio_latest_${{ matrix.os }}"
        path: "*.zip"
        if-no-files-found: error
        retention-days: 90
  windows_build:
    strategy:
      matrix:
        os: [windows-2019]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: 5.12.0
        modules: qtcharts qtopengl    
        
    - name: Download and Install Boost
      uses: MarkusJx/install-boost@v2.0.0      
      with:
        boost_version: 1.76.0
        boost_install_dir: ${{ github.workspace }}
    - name: get TIPL and DSI Studio atlas
      run: |
        git clone https://github.com/frankyeh/TIPL.git
        git clone https://github.com/frankyeh/DSI-Studio-atlas.git
        move ${{ github.workspace }}/boost ${{ github.workspace }}/boost_
        move ${{ github.workspace }}/boost_/boost/include/boost* ${{ github.workspace }}/boost__
        move ${{ github.workspace }}/boost__/boost ${{ github.workspace }}/boost
        dir ${{ github.workspace }}/boost
        
    - name: Build DSI Studio
      run: |
        for /f "usebackq delims=#" %%a in (`"%programfiles(x86)%\Microsoft Visual Studio\Installer\vswhere" -latest -property installationPath`) do call "%%a\Common7\Tools\VsDevCmd.bat" -arch=x64
        mkdir -p build
        cd build
        qmake ../dsi_studio.pro 
        nmake
      shell: cmd

    - name: Packaging
      run: |
        mkdir dsi_studio_win
        move other\color_map dsi_studio_win   
        move other\device.txt dsi_studio_win   
        move build\release\dsi_studio.exe dsi_studio_win
        windeployqt dsi_studio_win\dsi_studio.exe
        move DSI-Studio-atlas dsi_studio_win\atlas  
    - name: Zip Release
      uses: TheDoctor0/zip-release@0.6.0
      with:
        filename: dsi_studio_win.zip
        exclusions: .git
        path: dsi_studio_win
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: "dsi_studio_latest_${{ matrix.os }}"
        path: "*.zip"
        if-no-files-found: error
        retention-days: 90
