name: Build on Linux, Mac, Windows

on: [push]

jobs:
  linux-gcc-build:

    runs-on: ubuntu-latest

    env:
      CXX: g++-9
      CFLAGS: -Werror
      QT_SELECT: qt5

    steps:
    - uses: actions/checkout@v1

    - name: install dependencies
      run: |
         sudo apt update
         sudo apt full-upgrade -y 
         sudo apt install -y --no-install-recommends libboost-all-dev zlib1g-dev ca-certificates libqt5charts5-dev libqt5opengl5-dev
         sudo apt-get clean
    - name: get TIPL
      run: |
         git clone https://github.com/frankyeh/TIPL.git
         mv TIPL tipl
    - name: build
      run: |
         mkdir -p build
         cd build
         qmake ../dsi_studio.pro
         make
    - name: packaging
      run: |
         mkdir dsi_studio_ubuntu20.04
         cp -R other/*  dsi_studio_ubuntu20.04     
         chmod 755 build/dsi_studio
         mv build/dsi_studio  dsi_studio_ubuntu20.04 
         git clone https://github.com/frankyeh/DSI-Studio-atlas.git
         mv DSI-Studio-atlas  dsi_studio_ubuntu20.04/atlas   
         zip -r dsi_studio_ubuntu_20.04.zip  dsi_studio_ubuntu20.04
    - name: Create Release
      uses: ncipollo/release-action@v1.8.9
      with:
         allowUpdates: true
         bodyFile: dsi_studio_ubuntu_20.04.zip
         name:  dsi_studio_ubuntu_20.04
         prerelease: false
   
  
  macos-build:

    runs-on: macos-latest

    env:
      CFLAGS: -Werror

    steps:
    - uses: actions/checkout@v1

    - name: install dependencies
      run: |
         brew update
         brew info qt5
         brew install qt5
         brew install boost
         mv /usr/local/Cellar/boost/1.76.0/include /usr/local/Cellar/boost/1.76.0/boost
         ls /usr/local/Cellar/boost/1.76.0
         ls /usr/local/Cellar/boost/1.76.0/boost
    - name: get TIPL
      run: |
         git clone https://github.com/frankyeh/TIPL.git
         mv TIPL tipl
    - name: build
      run: |
         mkdir -p build
         cd build
         export PATH="/usr/local/opt/qt@5/bin:$PATH" && export LDFLAGS="-L/usr/local/opt/qt@5/lib" && export CPPFLAGS="-I/usr/local/opt/qt@5/include -I/usr/local/Cellar/boost/1.76.0" && export PKG_CONFIG_PATH="/usr/local/opt/qt@5/lib/pkgconfig"
         qmake ../dsi_studio.pro
         make
         cd ..
    - name: packaging
      run: |
         mv other/* build/dsi_studio.app/Contents/MacOS/
         git clone https://github.com/frankyeh/DSI-Studio-atlas.git
         mv DSI-Studio-atlas build/dsi_studio.app/Contents/MacOS/atlas
         mv build/dsi_studio.app .
         macdeployqt dsi_studio.app
         rm -v !(dsi_studio.dmg)
         
    - name: Create Release
      uses: ncipollo/release-action@v1.8.9
      with:
         allowUpdates: true
         bodyFile: dsi_studio.dmg
         name:  dsi_studio_mac
         prerelease: false
