name: Build Docker
on: workflow_dispatch
jobs:
  docker_build:
    runs-on: ubuntu-latest
    steps:
    - name: Current Time
      uses: srfrnk/current-time@v1.1.0
      with: 
        format: YYYY-MM-DD
    - name: Check time
      run: echo "dsistudio/dsistudio:chen-${{ steps.current-time.outputs.formattedTime }}"
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Log in to the Container registry
      uses: docker/login-action@v1 
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: build_packages/docker/Dockerfile
        push: true
        tags: "dsistudio/dsistudio:chen-${{ steps.current-time.outputs.formattedTime }}"
