name: Build Release QT6
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag'
        required: true
        default: '2021.12.03'
      release_name:
        description: 'Release Name'
        required: true
        default: '2021.12.03 "Chen" Release'
jobs:
  macos-build:
    strategy:
      matrix:
        os: [macos-11]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    env:
      CFLAGS: -Werror
    steps:
    - uses: actions/checkout@v1
    - name: Install Qt CMake Ninja Cuda
      run: |
        brew update
        brew install qt6 cmake ninja cuda
    - name: Download TIPL and Atlases
      run: |
        git clone https://github.com/frankyeh/TIPL.git
        git clone https://github.com/frankyeh/DSI-Studio-atlas.git
        rm -fr DSI-Studio-atlas/.git
        mv TIPL tipl
    - name: Build DSI Studio
      run: |
        mkdir -p build
        export PATH="/usr/local/opt/qt@5/bin:$PATH" && export LDFLAGS="-L/usr/local/opt/qt@5/lib" && export CPPFLAGS="-I/usr/local/opt/qt@5/include" && export PKG_CONFIG_PATH="/usr/local/opt/qt@5/lib/pkgconfig"
        cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DTIPL_DIR=.
        cmake --build build --parallel --target all --config Release
    - name: Packaging
      run: |
        dir build/*
        mv other/* build/dsi_studio.app/Contents/MacOS/
        mv DSI-Studio-atlas build/dsi_studio.app/Contents/MacOS/atlas
        mv build/dsi_studio.app .
        /usr/local/opt/qt@6/bin/macdeployqt dsi_studio.app
        zip -r dsi_studio_mac_qt6.zip dsi_studio.app
    - name: Create Release
      uses: ncipollo/release-action@v1.8.9
      with:
        allowUpdates: true
        artifacts: "*.zip"
        tag: ${{ github.event.inputs.tag }}
        name: ${{ github.event.inputs.release_name }}
        prerelease: false

  windows_build:
    strategy:
      matrix:
        os: [ windows-2019]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - name: Install Zlib
      run: |
        powershell -Command "(Invoke-WebRequest -Uri https://git.io/JnHTY -OutFile install_zlib.bat)"; ./install_zlib.bat; del install_zlib.bat
        del "C:/Program Files/zlib/lib/zlib.lib"
        del "C:/Program Files/zlib/bin/zlib.dll"
    - name: Install Cuda
      uses: Jimver/cuda-toolkit@v0.2.5
    - name: Install Ninja and CMake
      run: |    
        choco install ninja cmake
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: 6.2.0
        modules: addons.qtcharts qtopengl    
    - name: get TIPL and DSI Studio atlas
      run: |
        git clone https://github.com/frankyeh/TIPL.git
        git clone https://github.com/frankyeh/DSI-Studio-atlas.git
    - name: Build DSI Studio
      run: |
        for /f "usebackq delims=#" %%a in (`"%programfiles(x86)%\Microsoft Visual Studio\Installer\vswhere" -latest -property installationPath`) do call "%%a\Common7\Tools\VsDevCmd.bat" -arch=x64
        mkdir -p build
        cmake -S . -B ./build -DCMAKE_BUILD_TYPE=Release -DTIPL_DIR=. -G "Visual Studio 16 2019"
        cmake --build ./build --parallel --config Release
      shell: cmd

    - name: Packaging
      run: |
        dir *
        mkdir dsi_studio_win
        move other\color_map dsi_studio_win   
        move other\device.txt dsi_studio_win   
        move build\dsi_studio.exe dsi_studio_win
        windeployqt --no-translations --no-system-d3d-compiler --compiler-runtime --no-opengl-sw dsi_studio_win\dsi_studio.exe
        move DSI-Studio-atlas dsi_studio_win\atlas  

    - name: Download the SSL files
      uses: suisei-cn/actions-download-file@v1
      with:
        url: "https://indy.fulgan.com/SSL/openssl-1.0.2u-x64_86-win64.zip"
    - name: Download TinyFSL
      uses: suisei-cn/actions-download-file@v1
      with:
        url: "https://github.com/frankyeh/TinyFSL/releases/download/2021.12.03/tiny_fsl_win64.zip"
    - name: Extract zip files
      run: |
        7z e openssl-1.0.2u-x64_86-win64.zip
        move *.dll dsi_studio_win
        7z e tiny_fsl_win64.zip -odsi_studio_win\plugin
        rd dsi_studio_win\plugin\tiny_fsl
        del *.zip
    - name: Zip Release
      uses: TheDoctor0/zip-release@0.6.0
      with:
        filename: dsi_studio_win_qt6.zip
        exclusions: .git
        path: dsi_studio_win
    - name: Create Release
      uses: ncipollo/release-action@v1.8.9
      with:
        allowUpdates: true
        artifacts: "*.zip"
        tag: ${{ github.event.inputs.tag }}
        name: ${{ github.event.inputs.release_name }}
        prerelease: false  
