name: C/C++ CI

on: [push] 

jobs:
  build:

    runs-on: windows-2022

    steps:
    - name: configure
      run: |
        vswhere -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath
          
