name: C/C++ CI

on:
  push:
    tags:
      - "*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Get tag
      id: tag
      uses: dawidd6/action-get-tag@v1
    - name: Use tag
      run: echo ${{steps.tag.outputs.tag}}
