name: C/C++ CI

on: [push] 

jobs:
  build:

    runs-on: windows-2022

    steps:
    - name: configure
      run: |
        for /f "usebackq tokens=*" %%i in (`vswhere -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath`) do (
          set InstallDir=%%i
          call "%InstallDir%\Common7\Tools\vsdevcmd.bat"
        )
          
