name: Test Release 
on:
  workflow_dispatch:
jobs:
  Recon:
    runs-on: ubuntu-latest
    steps:
    - name: Download DSI Studio
      uses: suisei-cn/actions-download-file@v1
      with:
        url: "https://github.com/frankyeh/DSI-Studio/releases/download/2021.12.03/dsi_studio_ubuntu_2004.zip"
    - name: Download Test File
      uses: suisei-cn/actions-download-file@v1
      with:
        url: "${{ secrets.TEST_FILE }}"
    - name: Unzip Files
      run: |
        unzip dsi_studio_ubuntu_2004.zip
        unzip DSI-Studio-Test.zip
        
    - name: Test DTI Recon
      run: |
        ./dsi-studio/dsi_studio --source=./src/*.src.gz --action=rec --method=1
    - name: Test GQI Recon
      run: |
        ./dsi-studio/dsi_studio --source=./src/*.src.gz --action=rec
    - name: Test QSDR Recon
      run: |
        ./dsi-studio/dsi_studio --source=./src/*.src.gz --action=rec --method=7
        ls -l ./src/*.fib.gz
        if [ 'ls -l ./src/*.fib.gz | wc -l' -eq 15 ] then
           echo "Fib files generated" 
        else
           echo "Some fib files were not generated"
           exit 1
        fi
