name: Test Release 
on:
  workflow_dispatch:
jobs:
  Animal_Recon:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Environment
      uses: ./.github/workflows/test_env
      with:
        test_file: ${{ secrets.TEST_FILE }}
    - name: Test Recon
      run: |
        ./dsi-studio/dsi_studio --source=./animal_src/*.src.gz --action=rec --method=1 |& tee -a log.txt
        ./dsi-studio/dsi_studio --source=./animal_src/*.src.gz --action=rec |& tee -a log.txt
        ./dsi-studio/dsi_studio --source=./animal_src/*.src.gz --action=rec --method=7 |& tee -a log.txt
    - name: List output
      run: |  
        ls -l ./animal_src/*.fib.gz
        cat log.txt
        
  Human_Recon:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Environment
      uses: ./.github/workflows/test_env
      with:
        test_file: ${{ secrets.TEST_FILE }}
    - name: Test Recon
      run: |
        ./dsi-studio/dsi_studio --source=./human_src/*.src.gz --action=rec --method=1 |& tee -a log.txt
        ./dsi-studio/dsi_studio --source=./human_src/*.src.gz --action=rec |& tee -a log.txt
        ./dsi-studio/dsi_studio --source=./human_src/*.src.gz --action=rec --method=7 --template=0 |& tee -a log.txt
    - name: List output
      run: |  
        ls -l ./human_src/*.fib.gz   
        cat log.txt
