name: Test Release 
on:
  workflow_dispatch:
jobs:
  Animal_Recon:
    runs-on: ubuntu-latest
    steps:
    - name: Download Files
      run: |
        curl -L "https://github.com/frankyeh/DSI-Studio/releases/download/2021.12.03/dsi_studio_ubuntu_2004.zip" -o 1.zip
        curl -L "${{ secrets.TEST_FILE }}" -o 2.zip
        unzip 1.zip
        unzip 2.zip
        rm -fr *.zip
    - name: Test Recon
      run: |
        ./dsi-studio/dsi_studio --source=./animal_src/*.src.gz --action=rec --method=1
        ./dsi-studio/dsi_studio --source=./animal_src/*.src.gz --action=rec
        ./dsi-studio/dsi_studio --source=./animal_src/*.src.gz --action=rec --method=7
    - name: List output
      run: |  
        ls -l ./animal_src/*.fib.gz
        
  Human_Recon:
    runs-on: ubuntu-latest
    steps:
    - name: Download Files
      run: |
        curl -L "https://github.com/frankyeh/DSI-Studio/releases/download/2021.12.03/dsi_studio_ubuntu_2004.zip" -o 1.zip
        curl -L "${{ secrets.TEST_FILE }}" -o 2.zip
        unzip 1.zip
        unzip 2.zip
        rm -fr *.zip
    - name: Test Recon
      run: |
        ./dsi-studio/dsi_studio --source=./human_src/*.src.gz --action=rec --method=1
        ./dsi-studio/dsi_studio --source=./human_src/*.src.gz --action=rec
        ./dsi-studio/dsi_studio --source=./human_src/*.src.gz --action=rec --method=7
    - name: List output
      run: |  
        ls -l ./human_src/*.fib.gz        
