name: Test Release 
on:
  workflow_dispatch:
jobs:
  Animal_Recon:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Environment
      run: |
        curl -L "https://github.com/frankyeh/DSI-Studio/releases/download/2021.12.03/dsi_studio_ubuntu_2004.zip" | jar xv
        chmod 777 ./dsi-studio/dsi_studio
        curl -L ${{ secrets.TEST_FILE }} | jar xv
    - name: Test DTI/GQI Recon
      run: |  
        cd animal_src
        ../dsi-studio/dsi_studio --source=*.src.gz --action=rec --method=1 |& tee -a log.txt
        ls Chipamzee.src.gz.dti.fib.gz
        ls Marmoset.src.gz.dti.fib.gz
        ls Rat.src.gz.dti.fib.gz
        ls Rhesus.src.gz.dti.fib.gz
        echo --------------------------------------------------------------------------------------------------
        ../dsi-studio/dsi_studio --source=*.src.gz --action=rec |& tee -a log.txt
        ls Chipamzee.src.gz.gqi.1.25.fib.gz
        ls Marmoset.src.gz.gqi.1.25.fib.gz
        ls Rat.src.gz.gqi.1.25.fib.gz
        ls Rhesus.src.gz.gqi.1.25.fib.gz

    
  Human_Recon:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Environment
      run: |
        curl -L "https://github.com/frankyeh/DSI-Studio/releases/download/2021.12.03/dsi_studio_ubuntu_2004.zip" | jar xv
        chmod 777 ./dsi-studio/dsi_studio
        curl -L ${{ secrets.TEST_FILE }} | jar xv
    - name: Test GQI Recon
      run: |
        cd human_src
        ../dsi-studio/dsi_studio --source=*.src.gz --action=rec
        ls dHCP.src.gz.gqi.1.25.fib.gz

  Human_Tracking:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Environment
      run: |
        curl -L "https://github.com/frankyeh/DSI-Studio/releases/download/2021.12.03/dsi_studio_ubuntu_2004.zip" | jar xv
        chmod 777 ./dsi-studio/dsi_studio
    - name: Test Tracking
      run: |
        curl -L https://github.com/frankyeh/DSI-Studio-atlas/blob/main/ICBM152/ICBM152.fib.gz?raw=true -o ICBM152.fib.gz
        ./dsi-studio/dsi_studio --source=ICBM152.fib.gz --action=trk --output=icbm152.tt.gz --export=stat,tdi
        ls icbm152.tt.gz
        ls icbm152.tt.gz.tdi.nii.gz
        ls icbm152.tt.gz.stat.txt
        echo --------------------------------------------------------------------------------------------------
        ./dsi-studio/dsi_studio --source=ICBM152.fib.gz --action=trk --track_id=Arcuate_Fasciculus_L --output=AF_L.tt.gz
        ls AF_L.tt.gz
        echo --------------------------------------------------------------------------------------------------
        ./dsi-studio/dsi_studio --source=ICBM152.fib.gz --action=trk --roi=FreeSurferDKT_Cortical:left_precentral,dilate,dilate,smoothing --roi2=FreeSurferDKT_Cortical:right_precentral,dilate,dilate,smoothing --output=LR.tt.gz
        ls LR.tt.gz
        echo --------------------------------------------------------------------------------------------------
        ./dsi-studio/dsi_studio --source=ICBM152.fib.gz --action=trk --fiber_count=1000000 --output=no_file --connectivity=FreeSurferDKT_Cortical --connectivity_value=count,qa
        ls ICBM152.fib.gz.FreeSurferDKT_Cortical.count.pass.connectivity.mat
        ls ICBM152.fib.gz.FreeSurferDKT_Cortical.count.pass.connectogram.txt
        ls ICBM152.fib.gz.FreeSurferDKT_Cortical.count.pass.network_measures.txt
        ls ICBM152.fib.gz.FreeSurferDKT_Cortical.qa.pass.connectivity.mat
        ls ICBM152.fib.gz.FreeSurferDKT_Cortical.qa.pass.connectogram.txt
        ls ICBM152.fib.gz.FreeSurferDKT_Cortical.qa.pass.network_measures.txt
        
        
         
