name: Test Release 
on:
  workflow_dispatch:
jobs:
  Animal_Recon:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Environment
      uses: ./.github/workflows/test_env
      with:
        test_file: ${{ secrets.TEST_FILE }}
    - name: Test DTI Recon
      run: |  
        ./dsi-studio/dsi_studio --source=./animal_src/*.src.gz --action=rec --method=1 |& tee -a log.txt
        cat log.txt
    - name: Test GQI Recon
      run: |  
        ./dsi-studio/dsi_studio --source=./animal_src/*.src.gz --action=rec |& tee -a log.txt
        cat log.txt
        
  Human_Recon:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Environment
      uses: ./.github/workflows/test_env
      with:
        test_file: ${{ secrets.TEST_FILE }}
    - name: Test GQI Recon
      run: |
        cd animal_src
        ../dsi-studio/dsi_studio --source=*.src.gz --action=rec
        if [[ -f dHCP.src.gz.gqi.1.25_.fib.gz ]]; then 
          exit 1;
        fi
