name: Test Release 
on:
  workflow_dispatch:
jobs:
  Animal_Recon:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Environment
      uses: ./.github/workflows/test_env
      with:
        test_file: ${{ secrets.TEST_FILE }}
    - name: Test DTI Recon
      run: |  
        cd animal_src
        ../dsi-studio/dsi_studio --source=*.src.gz --action=rec --method=1 |& tee -a log.txt
        ls Chipamzee.src.gz.dti.fib.gz
        ls Marmoset.src.gz.dti.fib.gz
        ls Rat.src.gz.dti.fib.gz
        ls Rhesus.src.gz.dti.fib.gz
    - name: Test GQI Recon
      run: |  
        cd animal_src
        ../dsi-studio/dsi_studio --source=*.src.gz --action=rec |& tee -a log.txt
        ls Chipamzee.src.gz.gqi.1.25.fib.gz
        ls Marmoset.src.gz.gqi.1.25.fib.gz
        ls Rat.src.gz.dti.gqi.1.25.fib.gz
        ls Rhesus.src.gz.gqi.1.25.fib.gz
    - name: Upload Results
      uses: actions/upload-artifact@v2.3.1
      with:
        name: animal_src_log
        path: ./animal_src/log.txt
    
  Human_Recon:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Environment
      uses: ./.github/workflows/test_env
      with:
        test_file: ${{ secrets.TEST_FILE }}
    - name: Test GQI Recon
      run: |
        cd human_src
        ../dsi-studio/dsi_studio --source=*.src.gz --action=rec
        ls dHCP.src.gz.gqi.1.25.fib.gz
    - name: Upload Results
      uses: actions/upload-artifact@v2.3.1
      with:
        name: human_src_log
        path: ./human_src/log.txt
