name: Test Release 
on:
  workflow_dispatch:
jobs:
  Animal_Recon:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Environment
      uses: ./.github/workflows/test_env
      with:
        test_file: ${{ secrets.TEST_FILE }}
    - name: Test DTI Recon
      run: |  
        ./dsi-studio/dsi_studio --source=./animal_src/*.src.gz --action=rec --method=1 |& tee -a log.txt
    - name: Test GQI Recon
      run: |  
        ./dsi-studio/dsi_studio --source=./animal_src/*.src.gz --action=rec |& tee -a log.txt
        ls ./animal_src/*
    - name: Upload Results
      uses: actions/upload-artifact@v2.3.1
      with:
        name: log.txt
        path: .
    
  Human_Recon:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Environment
      uses: ./.github/workflows/test_env
      with:
        test_file: ${{ secrets.TEST_FILE }}
    - name: Test GQI Recon
      run: |
        cd human_src
        ../dsi-studio/dsi_studio --source=*.src.gz --action=rec
        ls ./human_src/*
    - name: File Existence
      uses: andstor/file-existence-action@v1.1.0
      with:
        files: ./human_src/dHCP
