name: Test Release 
on:
  workflow_dispatch:
jobs:
  test_dsistudio:
    runs-on: ubuntu-latest
    steps:
    - name: Download DSI Studio
      uses: suisei-cn/actions-download-file@v1
      with:
        url: "https://github.com/frankyeh/DSI-Studio/releases/download/2021.12.03/dsi_studio_ubuntu_2004.zip"
    - name: Download Test File
      uses: suisei-cn/actions-download-file@v1
      with:
        url: "${{ secrets.TEST_FILE }}"
    - name: Unzip Files
      run: |
        unzip dsi_studio_ubuntu_2004.zip
        unzip DSI-Studio-Test.zip
        ls -l
        ./dsi-studio/dsi_studio --source=./src/*.src.gz --action=rec
    
