name: Test Release 
on:
  workflow_dispatch:
jobs:
  Animal_Recon:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Environment
      run: |
        curl -L "https://github.com/frankyeh/DSI-Studio/releases/download/2021.12.03/dsi_studio_ubuntu_2004.zip" | jar xv
        curl -L ${{ secrets.TEST_FILE }} | jar xv
        chmod 777 ./dsi-studio/dsi_studio
        
    - name: Test DTI/GQI Recon
      run: |  
        cd animal_src
        ../dsi-studio/dsi_studio --source=*.src.gz --action=rec --method=1 |& tee -a log.txt
        ls Chipamzee.src.gz.dti.fib.gz
        ls Marmoset.src.gz.dti.fib.gz
        ls Rat.src.gz.dti.fib.gz
        ls Rhesus.src.gz.dti.fib.gz
        echo --------------------------------------------------------------------------------------------------
        ../dsi-studio/dsi_studio --source=*.src.gz --action=rec |& tee -a log.txt
        ls Chipamzee.src.gz.gqi.1.25.fib.gz
        ls Marmoset.src.gz.gqi.1.25.fib.gz
        ls Rat.src.gz.gqi.1.25.fib.gz
        ls Rhesus.src.gz.gqi.1.25.fib.gz

    
  Human_Recon:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Environment
      run: |
        curl -L "https://github.com/frankyeh/DSI-Studio/releases/download/2021.12.03/dsi_studio_ubuntu_2004.zip" | jar xv
        curl -L ${{ secrets.TEST_FILE }} | jar xv
        chmod 777 ./dsi-studio/dsi_studio
    - name: Test GQI Recon
      run: |
        cd human_src
        ../dsi-studio/dsi_studio --source=*.src.gz --action=rec --method=1
        ls dHCP.src.gz.dti.fib.gz 
        ../dsi-studio/dsi_studio --source=*.src.gz --action=rec
        ls dHCP.src.gz.gqi.1.25.fib.gz
        ../dsi-studio/dsi_studio --source=*.src.gz --action=rec --method=7 --template=0
        ls dHCP.src.gz.icbm152.qsdr.1.25.*
        
  Human_Tracking_QSDR:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Environment
      run: |
        curl -L "https://github.com/frankyeh/DSI-Studio/releases/download/2021.12.03/dsi_studio_ubuntu_2004.zip" | jar xv
        curl -L https://github.com/frankyeh/DSI-Studio-atlas/blob/main/ICBM152/ICBM152.fib.gz?raw=true -o ICBM152.fib.gz
        chmod 777 ./dsi-studio/dsi_studio
    - name: Tracking
      run: |
        ./dsi-studio/dsi_studio --source=ICBM152.fib.gz --action=trk --output=icbm152.tt.gz --export=stat,tdi
        ls icbm152.tt.gz
        ls icbm152.tt.gz.tdi.nii.gz
        ls icbm152.tt.gz.stat.txt
        echo --------------------------------------------------------------------------------------------------
        ./dsi-studio/dsi_studio --source=ICBM152.fib.gz --action=trk --track_id=Arcuate_Fasciculus_L --output=AF_L.tt.gz
        ls AF_L.tt.gz
        echo --------------------------------------------------------------------------------------------------
        ./dsi-studio/dsi_studio --source=ICBM152.fib.gz --action=trk --roi=FreeSurferDKT_Cortical:left_precentral,dilate,dilate,smoothing --roi2=FreeSurferDKT_Cortical:right_precentral,dilate,dilate,smoothing --output=LR.tt.gz
        ls LR.tt.gz
        echo --------------------------------------------------------------------------------------------------
        ./dsi-studio/dsi_studio --source=ICBM152.fib.gz --action=trk --fiber_count=1000000 --output=no_file --connectivity=FreeSurferDKT_Cortical --connectivity_value=count,qa
        ls ICBM152.fib.gz.tt.gz.FreeSurferDKT_Cortical.count.pass.connectivity.mat
        ls ICBM152.fib.gz.tt.gz.FreeSurferDKT_Cortical.count.pass.connectogram.txt
        ls ICBM152.fib.gz.tt.gz.FreeSurferDKT_Cortical.count.pass.network_measures.txt
        ls ICBM152.fib.gz.tt.gz.FreeSurferDKT_Cortical.qa.pass.connectivity.mat
        ls ICBM152.fib.gz.tt.gz.FreeSurferDKT_Cortical.qa.pass.connectogram.txt
        ls ICBM152.fib.gz.tt.gz.FreeSurferDKT_Cortical.qa.pass.network_measures.txt

  Human_Tracking_GQI:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Environment
      run: |
        curl -L "https://github.com/frankyeh/DSI-Studio/releases/download/2021.12.03/dsi_studio_ubuntu_2004.zip" | jar xv
        curl -L https://zenodo.org/record/6307812/files/100206.src.gz.gqi.1.7.fib.gz?download=1 -o 100206.fib.gz
        curl -L https://github.com/frankyeh/DSI-Studio-atlas/blob/main/ICBM152/ICBM152.QA.nii.gz?raw=true -o template_qa.nii.gz
        chmod 777 ./dsi-studio/dsi_studio
    - name: Tracking
      run: |
        ./dsi-studio/dsi_studio --source=100206.fib.gz --action=trk --output=100206.tt.gz --export=stat,tdi
        ls 100206.tt.gz
        ls 100206.tt.gz.tdi.nii.gz
        ls 100206.tt.gz.stat.txt
        echo --------------------------------------------------------------------------------------------------
        ./dsi-studio/dsi_studio --source=100206.fib.gz --action=trk --track_id=Arcuate_Fasciculus_L --output=AF_L.tt.gz
        ls AF_L.tt.gz
        echo --------------------------------------------------------------------------------------------------
        ./dsi-studio/dsi_studio --source=100206.fib.gz --action=trk --roi=FreeSurferDKT_Cortical:left_precentral,dilate,dilate,smoothing --roi2=FreeSurferDKT_Cortical:right_precentral,dilate,dilate,smoothing --output=LR.tt.gz
        ls LR.tt.gz
        echo --------------------------------------------------------------------------------------------------
        ./dsi-studio/dsi_studio --source=100206.fib.gz --action=trk --fiber_count=1000000 --output=no_file --connectivity=FreeSurferDKT_Cortical --connectivity_value=count,qa
        ls 100206.fib.gz.tt.gz.FreeSurferDKT_Cortical.count.pass.connectivity.mat
        ls 100206.fib.gz.tt.gz.FreeSurferDKT_Cortical.count.pass.connectogram.txt
        ls 100206.fib.gz.tt.gz.FreeSurferDKT_Cortical.count.pass.network_measures.txt
        ls 100206.fib.gz.tt.gz.FreeSurferDKT_Cortical.qa.pass.connectivity.mat
        ls 100206.fib.gz.tt.gz.FreeSurferDKT_Cortical.qa.pass.connectogram.txt
        ls 100206.fib.gz.tt.gz.FreeSurferDKT_Cortical.qa.pass.network_measures.txt
        echo --------------------------------------------------------------------------------------------------
        ./dsi-studio/dsi_studio --source=100206.fib.gz --action=trk --other_slices=template_qa.nii.gz --dt_threshold_index=template_qa-qa --seed_count=1000000 --dt_threshold=0.1 --output=dt.tt.gz
        ls dt.tt.gz
        
  Automatic_Tracking:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Environment
      run: |
        curl -L "https://github.com/frankyeh/DSI-Studio/releases/download/2021.12.03/dsi_studio_ubuntu_2004.zip" | jar xv
        curl -L https://zenodo.org/record/6307812/files/100206.src.gz.gqi.1.7.fib.gz?download=1 -o 1.fib.gz
        curl -L https://zenodo.org/record/6307812/files/100307.src.gz.gqi.1.7.fib.gz?download=1 -o 2.fib.gz
        curl -L https://github.com/frankyeh/DSI-Studio-atlas/blob/main/ICBM152/ICBM152.fib.gz?raw=true -o 3.fib.gz
        chmod 777 ./dsi-studio/dsi_studio
    - name: Tracking
      run: |
        ./dsi-studio/dsi_studio --source=*.fib.gz --action=atk --track_id=Optic,Arcuate,spinal
        ls -l
      
